# Generated by Django 3.0.3 on 2020-08-21 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200819_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 5, 12, 15, 13914, tzinfo=utc)),
        ),
    ]
